// The types of @deck/sdk, generated by scripts/build-types.mjs from deck's web SDK
// (apps/web/src/sdk/index.ts). Do not edit: run `pnpm --filter @deck/sdk types:build`.
import * as React from 'react';
import { ReactNode, ComponentProps, Component, ElementType, ReactElement } from 'react';
import { LucideIcon, LucideProps } from 'lucide-react';
import { RowData, ColumnDef } from '@tanstack/react-table';
export { ColumnDef } from '@tanstack/react-table';

/** A JSON value: what a manifest may contain so the kernel can read it without running code. */
type JsonPrimitive = string | number | boolean | null;
type JsonValue$1 = JsonPrimitive | JsonValue$1[] | JsonObject;
interface JsonObject {
    [key: string]: JsonValue$1;
}
/** A JSON Schema document or fragment, kept as plain JSON. */
type JsonSchema = JsonObject;
/** An RFC 6901 JSON Pointer, e.g. `/claude/statusLine/credentialEnv`. */
type JsonPointer = `/${string}` | "";

/**
 * A module manifest: everything the kernel needs to know about a module **without running
 * its code** — whether it is enabled, what config it owns, which provider kinds and UI
 * contributions it brings. It is plain JSON: built-ins write it in TypeScript, external
 * modules ship it as `deck-module.json`.
 */
interface ModuleManifest {
    /** Module id, lowercase kebab-case (`llm-usage`). Its config lives at `modules.<id>`. */
    id: string;
    /** The module's own semver. */
    version: string;
    /** Range of the kernel module API this module was written against, e.g. `^0.1`. */
    deckApi: string;
    /** Module ids that must be enabled and initialised first. */
    dependsOn?: string[];
    /**
     * When the module is enabled. `config`: its `modules.<id>` section is present. `env`: the
     * named variable is `true` or `1` (case-insensitive). Every given condition must hold;
     * absent means always on.
     */
    enabledBy?: {
        config?: true;
        env?: string;
    };
    /**
     * Environment variables the module owns and may read through `ctx.env`
     * (`^[A-Z][A-Z0-9_]*$`). A name is owned by one module: the host refuses a manifest that
     * declares a deployment setting the kernel reads (`DECK_DATA_DIR`, `DECK_PORT`, …) or a
     * name another module already owns (built-in modules claim first).
     */
    env?: string[];
    /**
     * Non-secret environment variables any module may read, and none owns (`TZ`,
     * `HTTPS_PROXY`). Never a kernel setting, never a name some module owns in `env`, and
     * never a credential: secrets belong in `env`, where they are the module's alone.
     */
    sharedEnv?: string[];
    /**
     * Pointers into the module's own config section whose string values name further readable
     * env vars (a config-named credential variable, for example). A resolved name must match
     * `^[A-Z][A-Z0-9_]*$`, and a deployment setting the kernel itself reads (`DECK_DATA_DIR`,
     * `DECK_SNAPSHOT_SOURCE`, …) is readable only when it is also listed in `env`.
     */
    envFromConfig?: JsonPointer[];
    config?: ModuleConfigDecl;
    providerKinds?: ProviderKindDecl[];
    /**
     * In-process services the module offers to, or reads from, other modules (see
     * `ServerModuleContext.services`). A module that `uses` a name initialises after every
     * running module that `provides` it.
     */
    services?: ModuleServicesDecl;
    contributes?: ModuleContributions;
    health?: ModuleHealthDecl;
    dataDir?: ModuleDataDirDecl;
}
interface ModuleServicesDecl {
    /** Service names the module may offer, `<namespace>/<name>` (`sources/reader`). */
    provides?: string[];
    /** Service names the module may read. A name is never both provided and used by one module. */
    uses?: string[];
}
interface ModuleDataDirDecl {
    /**
     * A directory directly under `$DECK_DATA_DIR` that predates the module (`actions`), used
     * by `ctx.dataDir()` in place of `modules/<id>` so existing data stays where it is. One
     * literal segment, not `modules`, and unique across modules. Built-in modules only: on
     * any other module it makes the manifest invalid.
     */
    legacyPath: string;
}
interface ModuleConfigDecl {
    /** JSON Schema fragment for the `modules.<id>` section. */
    schema: JsonSchema;
    /** Layer ownership of key paths, relative to the module section. */
    ownership?: Record<string, OwnerDecl>;
    /**
     * Identity fields for arrays, so layers merge their elements by identity rather than
     * position: relative key path → field names, or → `{ <type>: fields }` for an array of
     * items discriminated by a `type` field.
     */
    identity?: Record<string, string[] | Record<string, string[]>>;
    /**
     * Ids that must be unique, each entry one namespace that may span several arrays. A later
     * occurrence of a key already seen (in document order) is `ID_DUPLICATE`. An `identity` row
     * for an array a namespace covers only keys the layer merge; every other identity row is
     * checked for duplicates itself. When given, the list names at least one namespace.
     */
    unique?: UniqueDecl[];
    /** Finding codes this module's validation rules may emit. */
    findings?: FindingCodeDecl[];
    /**
     * Where the section names an estate host or service. The kernel resolves each one against
     * the estate, as it does its own references: `REF_HOST_UNRESOLVED` /
     * `REF_SERVICE_UNRESOLVED`, and in an overlay layer `OVERLAY_DANGLING_REF` against the base.
     */
    references?: ReferenceDecl[];
}
/**
 * A host/service reference in a module section. A string is a relative key path
 * (`actions[].target`) whose value is `{ host, service? }`, reported at the field that does
 * not resolve. The object form names the fields: `host` (default `"host"`) and `service`
 * (default `"service"`) are field names on the value at `path`, and `at: "element"` reports
 * a finding at the value itself rather than at the field. A value without a string host
 * field is not a reference and is skipped.
 */
type ReferenceDecl = string | {
    path: string;
    host?: string;
    service?: string;
    at?: "field" | "element";
};
/** One id namespace: see {@link ModuleConfigDecl.unique}. */
interface UniqueDecl {
    /**
     * Relative key paths of arrays, ending in `[]` (`groups[]`, `groups[].items[]`). Their
     * elements that carry every `key` field as an own property share the namespace; others are
     * skipped.
     */
    paths: string[];
    /** The fields whose values form the id. */
    key: string[];
    /**
     * The `ID_DUPLICATE` message; `{key}` is replaced by the id (a JSON string, or a
     * parenthesised tuple for a compound key). Default: a generic message.
     */
    message?: string;
}
type OwnerDecl = "base" | "overlay" | "both" | "container";
interface FindingCodeDecl {
    /** UPPER_SNAKE_CASE, unique across the kernel and every module. */
    code: string;
    severity: "error" | "warning" | "info";
    summary: string;
    fix: string;
}
interface ProviderKindDecl {
    kind: string;
    /** Schema for one `integrations[]`/`sources[]` instance of this kind. */
    instanceSchema?: JsonSchema;
    /** Which top-level instance list `instanceSchema` applies to; default `integrations`. */
    instanceList?: "integrations" | "sources";
    /** Never polled: its data is fixed at registration (e.g. `link`). */
    static?: boolean;
    /**
     * May appear in `hosts[].bindings` / `services[].bindings`; the server module must then
     * handle it (`kinds[kind].binding`). A binding of a kind not bindable is reported.
     */
    bindable?: boolean;
    /** Its data can drive a status tone. */
    statusCapable?: boolean;
    /**
     * How a binding of this kind gives a bound card (a portal service) its up or down status:
     * declared data the web reads, so any `bindable`, `statusCapable` kind drives cards with no
     * feature code. Only such a kind may declare it.
     */
    status?: ProviderStatusDecl;
    /** Finding codes the kind handler's `validate` and `validateBinding` rules may report. */
    findings?: FindingCodeDecl[];
    /**
     * The fixed, public provider id the kind's `instances` handler registers under (offered with
     * `fixedId: true`), such as `prometheus`. Declared so config validation can tell another
     * instance taking it apart. Honoured for built-in modules only.
     */
    fixedId?: string;
    /**
     * With `fixedId`: the environment variable whose non-empty value registers the fixed id with
     * no instance in the estate (as `snapshot`'s `DECK_SNAPSHOT_SOURCE`). Config validation then
     * reserves the id while the variable is set. Honoured for built-in modules only.
     */
    fixedIdEnv?: string;
}
/**
 * Where a binding's status is in provider data, and which values mean up. The bound item is
 * read from the provider (`provider`); it is up when every `up` condition holds, else down. A
 * provider with no data, or none for the item, says so (unreachable, not found).
 */
interface ProviderStatusDecl {
    /**
     * The provider a binding reads: `binding`, the one the kind's binding handler registers
     * under the binding's own id (one provider per binding, as `http-health`'s); `fixed`, the
     * kind's `fixedId` instance, shared by every binding (as `docker`'s).
     */
    provider: "binding" | "fixed";
    /**
     * The bound item: the element of the list at `list` (a key path of the data) whose `key`
     * field equals the binding's `binding` field (`{ list: "containers", key: "name", binding:
     * "container" }`). A binding without that field (text or a number) has no status from this
     * kind. Absent: the provider's data is the item.
     */
    match?: {
        list: string;
        key: string;
        binding: string;
    };
    /** The item is up when every condition holds (its field's value is one of `in`), else down. */
    up: StatusConditionDecl[];
}
/** A condition on a bound item: the value at `field` (a key path) is one of `in`. */
interface StatusConditionDecl {
    field: string;
    in: Array<string | number | boolean>;
}
/** An extension id: `<kind>:<module>/<name>`, e.g. `pill:llm-usage/summary`. */
type ExtensionId = `${string}:${string}/${string}`;
type Tone$1 = "ok" | "warn" | "danger" | "info" | "pending" | "neutral";
interface ModuleContributions {
    pages?: PageDecl[];
    nav?: NavDecl[];
    slots?: SlotDecl[];
    extensions?: ExtensionDecl[];
    widgetTypes?: WidgetTypeDecl[];
    statusMaps?: Record<string, StatusMapData>;
    /** Icon name → SVG markup (external modules; built-ins use the web icon registry). */
    icons?: Record<string, string>;
    routes?: RoutesDecl;
}
interface PageDecl {
    id: ExtensionId;
    path: string;
    title: string;
    icon?: string;
    /** Export name in the module's web component table. */
    component: string;
    /**
     * The page's default dashboard: what its component renders, in reading order. The UI
     * manifest resolves it (each widget addressable by `widget:<module>/<page name>.<id>`, so
     * an override can switch it off), and the page renders it.
     */
    layout?: PageLayoutDecl;
}
/** A module page's dashboard: sections in reading order. */
interface PageLayoutDecl {
    sections: PageSectionDecl[];
}
/**
 * One section of a module page's dashboard: the widgets a `widget` slot's extensions place
 * (`{ slot }`, a slot the module hosts), or widgets of the module's own types or core's.
 */
type PageSectionDecl = {
    slot: string;
} | {
    widgets: PageWidgetDecl[];
};
/**
 * A widget on a module page's dashboard. It reads no provider and takes no options: its
 * component brings its own data, and an operator's dashboard (`ui.pages`) places the type with
 * options and a source.
 */
interface PageWidgetDecl {
    /** Unique on the page: the widget is `widget:<module>/<page name>.<id>`. */
    id: string;
    type: `${string}/${string}`;
}
interface NavDecl {
    id: ExtensionId;
    /** Target page id, or an external/relative href. */
    page?: ExtensionId;
    href?: string;
    group: string;
    label?: string;
    icon?: string;
    order?: number;
}
interface SlotDecl {
    id: string;
    accepts: "pill" | "widget" | "entity-section" | "nav" | "page" | "action";
}
interface ExtensionDecl {
    id: ExtensionId;
    kind: string;
    attachTo: {
        slot: string;
        order?: number;
    };
    component?: string;
    widget?: JsonObject;
    config?: JsonObject;
    enabled?: boolean;
}
interface WidgetTypeDecl {
    /** `<module>/<widget>`. */
    type: `${string}/${string}`;
    optionsSchema: JsonSchema;
    component?: string;
    /** Provider kinds the widget can render. */
    sources?: string[];
    /**
     * Options whose values name entries of the module's own config section (not to be confused
     * with `config.references`, which resolve estate hosts and services): each value of
     * `option` (text, or a list of text) should be the `key` of an entry of `modules.<id>.<list>`.
     * One that is not is reported in the UI manifest (UI_WIDGET_OPTION_UNKNOWN); the widget
     * still renders, skipping it.
     */
    optionReferences?: WidgetOptionReferenceDecl[];
}
/** A widget option that names entries of its module's config section (`portal/groups`' `groups`). */
interface WidgetOptionReferenceDecl {
    option: string;
    /** The list in the module's section (`groups`). */
    list: string;
    /** The key of its entries the option names (`id`). */
    key: string;
}
interface StatusMapData {
    values?: Record<string, Tone$1>;
    rules?: StatusRule[];
}
interface StatusRule {
    lt?: number;
    lte?: number;
    gt?: number;
    gte?: number;
    eq?: string | number | boolean;
    tone: Tone$1;
}
interface RoutesDecl {
    /**
     * Extra prefixes the module's `/api/m/<id>` sub-app is also mounted at, for HTTP paths
     * that predate the module (e.g. `/api/llm-usage`). Literal paths under `/api/` only
     * (characters `A-Z a-z 0-9 . _ ~ - /`), outside `/api/m`, and not overlapping another
     * module's prefix or a kernel route.
     */
    legacyAliases?: string[];
    /**
     * Exact literal paths outside `/api` the module serves (e.g. `/metrics`). The SPA fallback
     * never rewrites them, even while the module is disabled.
     */
    rootPaths?: string[];
    /**
     * Fixed answers served at the module's prefixes (`/api/m/<id>` and every legacy alias)
     * while the module is installed but not running, so a client can still learn that the
     * capability is off. Without them those paths answer 404 like any unknown API path. No
     * module code runs for them.
     */
    whenDisabled?: DisabledRouteDecl[];
}
/** One fixed response a disabled module's prefixes answer. */
interface DisabledRouteDecl {
    method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
    /**
     * Path under the module's prefix: `""` for the prefix itself, else `/`-separated literal
     * or `:param` segments (`/runs/:runId/cancel`).
     */
    path: string;
    /** HTTP status, 200–599. */
    status: number;
    /** JSON response body. */
    body: JsonValue$1;
}
interface ModuleHealthDecl {
    /**
     * A top-level `/api/health` key that mirrors this module's reported `data`, for health
     * fields that predate the module (e.g. `llmUsage`). It cannot shadow a kernel field.
     */
    legacyKey?: string;
}

/**
 * The resolved UI manifest served at `GET /api/ui`: which modules are installed, and which of
 * their pages, nav entries, slots and extensions render, where and with what config, after
 * config overrides. The web shell renders from it; it is plain JSON.
 */
interface UiManifest {
    /** Version of this document's shape. */
    uiApi: 1;
    /** The shell's brand: the estate's name unless config sets one. */
    brand: UiBrand$1;
    /**
     * The page rendered at `/`: `ui.home` when it names a routed page with no path parameters,
     * else the portal's overview. `null` when neither is routed (then `/` is not found). Absent
     * only from an older server.
     */
    home?: UiHome | null;
    /** Every known module (enabled or not), by id. */
    modules: UiModule[];
    /** Slots that enabled modules host, by id. */
    slots: UiSlot[];
    /** Routed pages of enabled modules, by id. */
    pages: UiPage$1[];
    /**
     * Pages of disabled modules, by id: not routed, so the shell answers their path by saying
     * the module is off. A page whose path an enabled page or a root path serves, or whose path
     * is not a usable page path (a finding), is left out. An older server does not send it.
     */
    disabledPages?: UiDisabledPage[];
    /**
     * The groups of the `app/nav` entries, in sidebar order: the groups the ui config lists, in
     * its order, then any other group an entry names, by id. Only groups with an entry appear.
     */
    navGroups: UiNavGroup$1[];
    /** Nav entries of enabled modules, by group (in `navGroups` order), order, then id. */
    nav: UiNavItem$1[];
    /** Enabled extensions, by slot, order, then id. */
    extensions: UiExtension[];
    /** Registered provider instances, by id. */
    providers: UiProvider[];
    /**
     * The bindable, status-capable provider kinds of enabled modules that declare how a binding
     * gives a card its status, by kind: what a portal card's status reads. An older server does
     * not send it.
     */
    statusKinds?: UiStatusKind[];
    /**
     * The widget types of enabled modules (and the kernel's `core/…`), by type: what a config
     * page's widget may name. An older server does not send it.
     */
    widgetTypes?: UiWidgetType[];
    /**
     * The ui config's status maps (`ui.statusMaps`), by name: what a widget's `statusMap` option
     * names, read with `statusTone`. Absent when the config declares none.
     */
    statusMaps?: Record<string, StatusMapData>;
    /**
     * `true` when the ui config allows embeds (`ui.allowUnsafeEmbeds`): only then does a
     * `core/embed` widget frame its page. Absent otherwise.
     */
    allowUnsafeEmbeds?: true;
    /**
     * The SVG icons enabled modules contribute (`contributes.icons`), by name (`<module>/<name>`):
     * what `Icon` renders for a name outside deck's curated set. Absent when there are none.
     */
    icons?: Record<string, string>;
    /** Problems found while resolving; none of them stops the UI from rendering. */
    findings: UiFinding[];
}
interface UiBrand$1 {
    /** The product name the shell shows (sidebar header, document title). */
    title: string;
    /** An icon name for the sidebar mark, in place of the title's initial (`ui.brand.icon`). */
    icon?: string;
    /** An http(s) URL or root-relative path of a logo image for the sidebar mark (`ui.brand.logoUrl`). */
    logoUrl?: string;
}
/** The home page: the page `/` renders, which also stays routed at its own path. */
interface UiHome {
    page: ExtensionId;
    /** The page's own path. */
    path: string;
}
interface UiNavGroup$1 {
    id: string;
    /** The group heading. */
    label: string;
    icon?: string;
}
interface UiModule {
    id: string;
    version: string;
    enabled: boolean;
    /** Why the module is not enabled; absent when enabled. */
    reason?: string;
    /** `module`: a module on the module contract; `kernel`: a feature still wired into the kernel. */
    origin: "module" | "kernel";
    /**
     * The settings that would switch the module on, when their being unset is why the module is
     * off: its own unmet switches, and those of a dependency that is off only because of its
     * own. Each is an env var's name or a config key; names only, never values. Absent when no
     * setting would enable the module; never empty.
     */
    enabledBy?: UiModuleSwitch[];
    /**
     * Where the module's web half loads from: set only for an enabled runtime module whose code
     * deck loaded and that has one. The shell imports `script` (native ESM, through the page's
     * import map) after this manifest, with `styles` linked first.
     */
    web?: UiModuleWeb;
}
/** A runtime module's web half: root-relative URLs under `/modules/<id>/`. */
interface UiModuleWeb {
    script: string;
    styles?: string;
}
/** An env var (`DECK_ACTIONS_ENABLED`) or a config key (`modules.<id>`) that enables a module. */
type UiModuleSwitch = {
    env: string;
} | {
    config: string;
};
/** A page of a disabled module, as declared. */
interface UiDisabledPage {
    id: ExtensionId;
    module: string;
    path: string;
    title: string;
    icon?: string;
}
interface UiSlot {
    id: string;
    accepts: SlotDecl["accepts"];
    /** The module hosting the slot (`core` for the shell's own slots). */
    module: string;
}
interface UiPage$1 {
    id: ExtensionId;
    module: string;
    path: string;
    title: string;
    icon?: string;
    /** Export name in the module's web component table (`ConfigPage` for a config page). */
    component: string;
    /**
     * The page's sections and widgets: a config page's (`ui.pages`), or the default dashboard a
     * module declares for its page (the portal's), with overrides applied.
     */
    layout?: UiPageLayout;
}
/** A page's body: its sections, in reading order. */
interface UiPageLayout {
    sections: UiLayoutSection[];
}
/** One section of a page's layout: widgets in a grid, or the widgets a slot places. */
type UiLayoutSection = UiWidgetSection | UiSlotSection;
/**
 * The widgets a `widget` slot's extensions place (a module page's `{ slot }` section), in the
 * manifest's order for that slot. Listed only while the slot's host is enabled.
 */
interface UiSlotSection {
    slot: string;
}
/**
 * One section of widgets: a heading over a grid, one column below `md`. A config page's always
 * has a title; a module page's has none, and its page decides how its widgets render.
 */
interface UiWidgetSection {
    title?: string;
    /** Grid columns from the `md` breakpoint up. */
    columns: 1 | 2 | 3 | 4;
    /** Its widgets, in reading order (DOM order). */
    widgets: UiWidgetInstance[];
}
/** A widget placed on a config page: a widget descriptor with its source resolved. */
interface UiWidgetInstance {
    /**
     * `widget:ui/<page>.<id>` from the widget's `id`, else positional (`widget:ui/<page>.s<N>w<M>`,
     * 1-based), which changes when sections or widgets move.
     */
    id: ExtensionId;
    /** The widget type, `<module>/<name>`. */
    type: string;
    title?: string;
    /**
     * The provider it reads, resolved from its `source` (an id, or the first provider of a
     * kind); `null` when it names none, or one that is not registered (a finding).
     */
    source: UiProvider | null;
    /** Why its `source` resolved to no provider (it renders an error state); absent otherwise. */
    sourceProblem?: string;
    /**
     * Why it cannot render: no enabled module provides its type. It then reads no source and has
     * no projection, and renders as unavailable. Absent otherwise.
     */
    typeProblem?: string;
    /** Its JMESPath `select`, which the server evaluates over the provider's data at each poll. */
    select?: string;
    /**
     * The key of its `select` result in the provider envelope's `projections` (its id); absent
     * when it has no `select`, and it reads the envelope's `data` whole.
     */
    projection?: string;
    options: JsonObject;
    /**
     * `external` on a widget a module contributes at runtime (a sidecar's): every link it renders
     * from markdown (its content, raw HTML in it, or text from its source) keeps only an absolute
     * http(s) href, shown as an external link; any other becomes plain text. Absent otherwise.
     */
    linkPolicy?: "external";
    /** Columns spanned, at most the section's. */
    span: 1 | 2 | 3 | 4;
    rows: number;
}
/** A provider kind whose bindings give cards a status, and how (its module's declaration). */
interface UiStatusKind {
    kind: string;
    module: string;
    /** The provider every binding of the kind reads, when its status reads the kind's fixed instance. */
    fixedId?: string;
    status: ProviderStatusDecl;
}
/** A widget type a module provides. */
interface UiWidgetType {
    type: string;
    module: string;
    /** Provider kinds it can render; absent means any. */
    sources?: string[];
}
/**
 * A nav entry: a module's, or one the ui config adds (`ui.nav.items`, listed with module
 * `ui`, `UI_CONFIG_MODULE`): a link to a page, an href, or a separator.
 */
interface UiNavItem$1 {
    id: ExtensionId;
    module: string;
    /** The nav slot the entry attaches to (`app/nav` unless an override re-attaches it). */
    slot: string;
    page?: ExtensionId;
    /** An in-app path, or an external `http(s)` URL the shell opens in a new tab. */
    href?: string;
    group: string;
    /** The entry's label, defaulting to its page's title; empty for a separator. */
    label: string;
    /** The entry's icon, defaulting to its page's icon. */
    icon?: string;
    order: number;
    /** A divider between the group's entries, with no page or href. */
    separator?: true;
}
interface UiExtension {
    id: ExtensionId;
    kind: string;
    module: string;
    slot: string;
    order: number;
    component?: string;
    widget?: JsonObject;
    config?: JsonObject;
}
interface UiProvider {
    id: string;
    kind: string;
}
type UiFindingCode = "UI_UNKNOWN_EXTENSION" | "UI_UNKNOWN_SLOT" | "UI_PAGE_PATH_COLLISION" | "UI_DUPLICATE_ID" | "UI_SLOT_KIND_MISMATCH" | "UI_INVALID_OVERRIDE" | "UI_INVALID_PAGE" | "UI_HOME_UNKNOWN" | "UI_HOME_DISABLED" | "UI_HOME_NOT_ROUTABLE"
/** The config directory changed and no longer loads: the last good config is still served. */
 | "UI_CONFIG_INVALID"
/** The config directory changed outside `ui`: that change takes effect when deck restarts. */
 | "UI_RESTART_REQUIRED" | "UI_WIDGET_SOURCE_UNKNOWN" | "UI_WIDGET_SOURCE_KIND" | "UI_WIDGET_SPAN"
/** A widget option names an entry its module's config does not have (a `portal/groups` group id). */
 | "UI_WIDGET_OPTION_UNKNOWN"
/** A bindable, status-capable provider kind declares no `status`, so its bindings give cards none. */
 | "UI_STATUS_UNDECLARED" | "UI_OVERRIDE_POSITIONAL"
/** A remote integration's latest describe was refused; its last good one (if any) still renders. */
 | "REMOTE_DESCRIBE_INVALID"
/** A remote integration's sidecar could not be asked to describe itself; its last good describe (if any) still renders. */
 | "REMOTE_DESCRIBE_UNREACHABLE"
/** A sidecar's describe names another id than its integration's, which deck uses. */
 | "REMOTE_DESCRIBE_ID_MISMATCH"
/** A sidecar's describe lists nav entries, but its page has no sidebar entry to group them with. */
 | "REMOTE_NAV_UNPLACED";
interface UiFinding {
    code: UiFindingCode;
    /** `info` only for what works as configured but is fragile (UI_OVERRIDE_POSITIONAL). */
    severity: "warning" | "info";
    message: string;
    /** The extension, page, nav or nav group id the finding is about. */
    id?: string;
    slot?: string;
}

/**
 * The kernel's module API version. Modules declare a compatible range in `deckApi`.
 * It stays at 0.x until the contract freezes; on 0.x every minor bump may break.
 */
declare const DECK_API_VERSION = "0.1.0";
/**
 * Whether `version` (default: the kernel's) satisfies a module's `deckApi` range.
 * Caret ranges follow npm semantics: `^1.2` allows `>=1.2.0 <2.0.0`; on 0.x the minor is the
 * breaking component, so `^0.1` allows `>=0.1.0 <0.2.0`; on 0.0.x every patch is, so `^0.0.3`
 * allows only `0.0.3` while `^0.0` allows any `0.0.x`. An unsupported range never matches.
 */
declare function satisfiesDeckApi(range: string, version?: string): boolean;

/**
 * The part of a manifest the web half reads: the module's identity and its UI contributions
 * (pages, nav entries, slots, extensions). It has no `routes`, which are server-only: a
 * built-in's shared copy cannot declare them, so the server manifest that spreads it in owns
 * its routes alone. A full {@link ModuleManifest} value is still accepted where one is
 * expected, so an external module passes its whole manifest.
 */
type WebModuleManifest = Pick<ModuleManifest, "id" | "version" | "deckApi"> & {
    contributes?: Omit<ModuleContributions, "routes">;
};
/**
 * A module's web half: a table of components that the manifest's pages, extensions and
 * widget types name. Where each one renders is data (manifest defaults, config overrides).
 */
interface WebModule<Components extends Record<string, unknown> = Record<string, unknown>> {
    readonly manifest: WebModuleManifest;
    readonly components: Readonly<Components>;
}
declare function defineWebModule<Components extends Record<string, unknown>>(manifest: WebModuleManifest, parts: {
    components: Components;
}): WebModule<Components>;

/**
 * A value's tone under a status map (`ui.statusMaps`), or `undefined` when the map gives it
 * none (the widget shows it untoned):
 * - its entry in `values`, when the value is text, a number or a boolean whose text is a key
 *   there (`404`, `true` and `"running"` all compare as text);
 * - else the first rule whose every condition holds, in order: `lt`/`lte`/`gt`/`gte` hold for a
 *   number, or text that reads wholly as one (`" 42 "` does not), and `eq` for an equal value,
 *   either way round: as numbers when either side is a number and both read as one (`0` and
 *   `"0.0"`), else as text (`true` and `"true"`); a rule with no condition matches any value.
 * Read leniently: a malformed map or rule (config validation refuses them) matches nothing.
 */
declare function statusTone(map: StatusMapData | undefined, value: unknown): Tone$1 | undefined;

/**
 * What kind of host this is.
 */
type HostKind = ("bare-metal" | "vm" | "lxc" | "appliance" | "endpoint" | "unknown");
/**
 * Declared lifecycle status rather than observed state.
 */
type HostStatus = ("active" | "planned" | "retired");
/**
 * An opaque secret reference id, never a secret value.
 */
type SecretRef = string;
/**
 * What kind of service this is.
 */
type ServiceKind = ("docker-compose" | "systemd" | "appliance" | "container" | "external");
/**
 * Declared lifecycle status rather than observed state.
 */
type ServiceStatus = ("active" | "planned" | "retired");
type UiNavItem = ({
    /**
     * The entry id, in the reserved ui namespace: nav:ui/<name>, such as nav:ui/grafana.
     */
    id: string;
    /**
     * The group the entry belongs to.
     */
    group: string;
    /**
     * The entry's label.
     */
    label: string;
    /**
     * An external http(s) URL.
     */
    href: string;
    /**
     * An icon name from the shell's icon set.
     */
    icon?: string;
    /**
     * Order within the group; default 100.
     */
    order?: number;
} | {
    /**
     * The separator's id, nav:ui/<name>.
     */
    id: string;
    /**
     * The group the separator belongs to.
     */
    group: string;
    /**
     * Marks the entry as a separator.
     */
    separator: true;
    /**
     * Order within the group; default 100.
     */
    order?: number;
});
type UiOverride = (boolean | {
    /**
     * Whether it renders.
     */
    enabled?: boolean;
    /**
     * Where it attaches, replacing its default (and an earlier layer's attachTo) whole; an omitted slot keeps the slot, an omitted order is 100, and group (nav entries only) when omitted keeps the entry's own.
     */
    attachTo?: {
        /**
         * The slot id.
         */
        slot?: string;
        /**
         * Order within the slot.
         */
        order?: number;
        /**
         * For a nav entry, the group it moves to.
         */
        group?: string;
    };
    /**
     * Replaces the extension's config (and an earlier layer's) wholesale.
     */
    config?: {
        [k: string]: JsonValue | undefined;
    };
});
/**
 * Any value representable in JSON.
 */
type JsonValue = (string | number | boolean | null | JsonValue[] | {
    [k: string]: JsonValue | undefined;
});
type UiWidget = UiWidget1;
/**
 * A status tone: the shell picks its colours and icon; config never carries a colour.
 */
type UiTone = ("ok" | "warn" | "danger" | "info" | "pending" | "neutral");
/**
 * A status tone: the shell picks its colours and icon; config never carries a colour.
 */
type UiTone1 = ("ok" | "warn" | "danger" | "info" | "pending" | "neutral");
/**
 * A merged deck config document containing projected estate inventory and presentation data.
 */
interface DeckConfigDocument {
    /**
     * The config schema version.
     */
    schemaVersion: 2;
    estate: Estate;
    /**
     * Declared hosts; absent is equivalent to an empty array.
     */
    hosts?: Host[];
    /**
     * Declared services; absent is equivalent to an empty array.
     */
    services?: Service[];
    /**
     * Document and configuration source declarations; absent is equivalent to an empty array.
     */
    sources?: Source[];
    /**
     * External tool integrations; absent is equivalent to an empty array.
     */
    integrations?: Integration[];
    ui?: Ui;
    /**
     * Module settings keyed by module id; each module contributes its own section schema.
     */
    modules?: {
        [k: string]: unknown | undefined;
    };
    /**
     * Integrity pins for runtime modules in DECK_MODULES_DIR, keyed by module id: a pinned module's code loads only when its directory matches the digest.
     */
    moduleIntegrity?: {
        /**
         * sha256-<base64> digest of the module directory, as `deck module digest <dir>` prints it.
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$".
         */
        [k: string]: string | undefined;
    };
}
/**
 * Estate-wide identity and conventions.
 */
interface Estate {
    /**
     * Human-readable estate name shown in the shell header.
     */
    name: string;
    /**
     * Per-network domain suffixes keyed by network label.
     */
    domains?: {
        /**
         * A domain suffix for the network named by the key.
         */
        [k: string]: string | undefined;
    };
    /**
     * IANA timezone name used by consumers for display.
     */
    timezone?: string;
    /**
     * Freshness defaults consumers use to derive staleness.
     */
    freshness?: {
        /**
         * ISO-8601 duration after which a snapshot is considered stale.
         */
        snapshotStaleAfter?: string;
    };
}
interface Host {
    /**
     * Host name, unique across the config.
     */
    name: string;
    kind: HostKind;
    /**
     * One-line statement of what the host is for.
     */
    purpose: string;
    status?: HostStatus;
    /**
     * Name of the host that runs this guest; required with vmid.
     */
    hypervisor?: string;
    /**
     * Numeric guest id on its hypervisor; required with hypervisor.
     */
    vmid?: number;
    /**
     * Network addresses labelled by network.
     */
    addresses?: Address[];
    access?: Access;
    backup?: Backup;
    /**
     * Live config files mapped to source-of-truth files.
     */
    managedConfigs?: ManagedConfig[];
    /**
     * Filesystem root under which container stacks live.
     */
    stacksRoot?: string;
    /**
     * Opaque secret references this host depends on.
     */
    secrets?: SecretRef[];
    /**
     * Presentation links shown on the host card.
     */
    links?: Link[];
    bindings?: Bindings;
    /**
     * Hide this host from default views without affecting validation.
     */
    hidden?: boolean;
}
interface Address {
    /**
     * Network label for this address (e.g. lan, tailnet). An open label — the same vocabulary Estate.domains keys off.
     */
    network: string;
    /**
     * The address on that network.
     */
    address: string;
    /**
     * Whether this is the host's primary address on that network.
     */
    primary?: boolean;
}
/**
 * Reachability and collection-method summary, never credentials.
 */
interface Access {
    /**
     * Whether the host is expected to be reachable.
     */
    reachable?: boolean;
    /**
     * Expected collection or access method.
     */
    method?: ("ssh" | "api" | "none");
    /**
     * Network port used by the access method.
     */
    port?: number;
    /**
     * Non-secret user name used for access.
     */
    user?: string;
    /**
     * Whether privileged elevation is expected.
     */
    sudo?: boolean;
    /**
     * Additional non-secret access notes.
     */
    notes?: string;
}
/**
 * Backup expectations for this host.
 */
interface Backup {
    /**
     * Whether this entity is expected to be backed up.
     */
    expected: boolean;
    /**
     * Human-readable backup schedule.
     */
    schedule?: string;
    /**
     * Non-secret backup destination identifier.
     */
    target?: string;
    /**
     * Additional backup notes.
     */
    notes?: string;
}
interface ManagedConfig {
    /**
     * Live configuration file path.
     */
    path: string;
    /**
     * Owning source-of-truth file reference.
     */
    source: string;
    /**
     * Additional management notes.
     */
    notes?: string;
}
interface Link {
    /**
     * Human-readable link label.
     */
    title: string;
    /**
     * Link target URL.
     */
    href: string;
    /**
     * Optional icon token.
     */
    icon?: string;
}
/**
 * Live-provider bindings keyed by provider kind.
 */
interface Bindings {
    [k: string]: unknown | undefined;
}
interface Service {
    /**
     * Service name, unique per host.
     */
    name: string;
    /**
     * Name of the host this service runs on.
     */
    host: string;
    kind: ServiceKind;
    /**
     * One-line statement of what the service is for.
     */
    purpose: string;
    status?: ServiceStatus;
    /**
     * Stack directory when it differs from the service name.
     */
    stack?: string;
    /**
     * Opaque secret references this service depends on.
     */
    secrets?: SecretRef[];
    backup?: Backup1;
    /**
     * Presentation links shown on the service card.
     */
    links?: Link[];
    bindings?: Bindings1;
    /**
     * Hide this service from default views without affecting validation.
     */
    hidden?: boolean;
}
/**
 * Backup expectations for this service.
 */
interface Backup1 {
    /**
     * Whether this entity is expected to be backed up.
     */
    expected: boolean;
    /**
     * Human-readable backup schedule.
     */
    schedule?: string;
    /**
     * Non-secret backup destination identifier.
     */
    target?: string;
    /**
     * Additional backup notes.
     */
    notes?: string;
}
/**
 * Live-provider bindings keyed by provider kind.
 */
interface Bindings1 {
    [k: string]: unknown | undefined;
}
interface Source {
    /**
     * Source id, unique across sources.
     */
    id: string;
    /**
     * Open source kind string.
     */
    kind: string;
    /**
     * Human-readable source title.
     */
    title: string;
    /**
     * Filesystem or repository source location.
     */
    location: {
        /**
         * Filesystem path to the source root.
         */
        path?: string;
        /**
         * Repository reference.
         */
        repo?: string;
        /**
         * Optional revision or branch.
         */
        ref?: string;
    };
    /**
     * Optional include glob patterns.
     */
    include?: string[];
    /**
     * Optional exclude glob patterns.
     */
    exclude?: string[];
    /**
     * Optional owning host or service.
     */
    owner?: {
        /**
         * Owning host name.
         */
        host: string;
        /**
         * Optional owning service name on that host.
         */
        service?: string;
    };
    /**
     * Environment variable name holding a credential, never its value.
     */
    credentialEnv?: string;
}
interface Integration {
    /**
     * Integration id, unique across integrations.
     */
    id: string;
    /**
     * Open provider kind string.
     */
    kind: string;
    /**
     * Human-readable integration title.
     */
    title: string;
    /**
     * Base URL of the integrated tool.
     */
    baseUrl: string;
    /**
     * Optional deep-link template into the tool.
     */
    deepLink?: string;
    /**
     * Opaque provider-defined card specification.
     */
    card?: {
        [k: string]: unknown | undefined;
    };
    /**
     * Environment variable name holding a credential, never its value.
     */
    credentialEnv?: string;
}
/**
 * Presentation settings: brand, theme, home page, navigation and extension overrides.
 */
interface Ui {
    brand?: UiBrand;
    theme?: UiTheme;
    /**
     * The id of the page rendered at /, such as page:inventory/hosts; default the built-in home page.
     */
    home?: string;
    nav?: UiNav;
    /**
     * Overrides by extension, page or nav entry id. They replace, never merge: false disables, an object replaces attachTo and/or config, and a later layer's attachTo or config replaces an earlier layer's whole.
     */
    extensions?: {
        [k: string]: UiOverride | undefined;
    };
    /**
     * Config-defined pages (dashboards): sections of widgets, each page routed as page:ui/<id>.
     */
    pages?: UiPage[];
    /**
     * Let core/embed widgets show other sites' pages in sandboxed frames; default false, when each shows that embeds are off.
     */
    allowUnsafeEmbeds?: boolean;
    /**
     * Origins besides deck's own that may show deck in a frame (Content-Security-Policy frame-ancestors), such as https://ha.example.net or https://*.example.net; no path. Default none: only deck's own origin may frame it.
     *
     * @maxItems 32
     */
    frameAncestors?: string[];
    /**
     * While ui.allowUnsafeEmbeds is true, origins besides the core/embed URLs' own that framed pages may load or redirect to (Content-Security-Policy frame-src), such as a sign-in page: https://auth.example.net; no path. Deck's own origin is never allowed.
     *
     * @maxItems 32
     */
    frameSources?: string[];
    /**
     * Named maps from a widget's values to status tones, which widget options reference by name (statusMap).
     */
    statusMaps?: {
        [k: string]: UiStatusMap | undefined;
    };
}
/**
 * The product name and mark the shell shows.
 */
interface UiBrand {
    /**
     * The product name in the sidebar and the document title; default estate.name, then Deck.
     */
    title?: string;
    /**
     * An icon name from the shell's icon set, or one a module contributes (<module>/<name>), shown in place of the title's initial.
     */
    icon?: string;
    /**
     * An http(s) URL or a root-relative path to a logo image, shown in place of the icon.
     */
    logoUrl?: string;
}
/**
 * The operator's theme defaults; a viewer's own choice of mode still wins.
 */
interface UiTheme {
    /**
     * The colour mode a viewer who has not chosen one sees; default system.
     */
    mode?: ("light" | "dark" | "system");
    /**
     * The named colour preset, a contrast-tested token set; default teal.
     */
    preset?: ("teal" | "slate" | "copper" | "rose" | "high-contrast");
    /**
     * Spacing of tables, lists and sections; default comfortable.
     */
    density?: ("compact" | "comfortable");
    /**
     * Corner radius scale; default md.
     */
    radius?: ("none" | "sm" | "md" | "lg");
}
/**
 * Sidebar group order, labels and icons, and extra nav entries.
 */
interface UiNav {
    /**
     * Groups in sidebar order; the built-in groups not listed follow in their default order, then any other group by id. Across layers groups merge by id: a group keeps its first layer's position and a new id is appended.
     */
    groups?: UiNavGroup[];
    /**
     * Extra nav entries: external links and separators.
     */
    items?: UiNavItem[];
}
interface UiNavGroup {
    /**
     * The group id, a built-in group or a new one.
     */
    id: string;
    /**
     * The group heading; default the built-in heading, else the id.
     */
    label?: string;
    /**
     * An icon name from the shell's icon set.
     */
    icon?: string;
}
interface UiPage {
    /**
     * The page's name; its id is page:ui/<id>.
     */
    id: string;
    /**
     * The page's path, such as /lab: literal segments only.
     */
    path: string;
    /**
     * The page heading, nav label and document title.
     */
    title: string;
    /**
     * An icon name from the shell's icon set.
     */
    icon?: string;
    nav?: UiPageNav;
    /**
     * The page's sections, in reading order.
     *
     * @minItems 1
     */
    sections: [UiSection, ...(UiSection)[]];
}
/**
 * The page's sidebar entry (nav:ui/<id>); without it the page has none.
 */
interface UiPageNav {
    /**
     * The nav group the entry belongs to.
     */
    group: string;
    /**
     * The entry's label; default the page title.
     */
    label?: string;
    /**
     * Order within the group; default 100.
     */
    order?: number;
}
interface UiSection {
    /**
     * The section heading.
     */
    title: string;
    /**
     * Grid columns from the md breakpoint up (one column below it); default 1.
     */
    columns?: number;
    /**
     * The section's widgets, in reading order.
     *
     * @minItems 1
     */
    widgets: [UiWidget, ...(UiWidget)[]];
}
interface UiWidget1 {
    /**
     * A stable name, unique on the page; its id is widget:ui/<page>.<id>. Without one, the id is positional (s<N>w<M>, a form an id may not take) and changes when widgets move.
     */
    id?: string;
    /**
     * The widget type, <module>/<name>, such as core/json.
     */
    type: string;
    /**
     * The widget's heading.
     */
    title?: string;
    /**
     * The provider the widget reads: a provider id, or the first provider of a kind.
     */
    source?: (string | {
        /**
         * A provider kind.
         */
        kind: string;
    });
    /**
     * A JMESPath expression over the provider's data, evaluated on the server when the data changes, within fixed size and work limits.
     */
    select?: string;
    /**
     * Options of the widget type, checked against its schema.
     */
    options?: {
        [k: string]: JsonValue | undefined;
    };
    /**
     * Columns the widget spans; default 1, at most the section's columns.
     */
    span?: number;
    /**
     * Rows the widget spans; default 1.
     */
    rows?: number;
}
/**
 * A value's tone: its entry in values when it has one, else the first rule it satisfies, else none (neutral).
 */
interface UiStatusMap {
    /**
     * Exact values (text, numbers and booleans compared as text, such as running or 404) and their tones.
     */
    values?: {
        [k: string]: UiTone | undefined;
    };
    /**
     * Rules tried in order; the first whose every condition holds gives the tone. A rule with no condition matches any value.
     *
     * @minItems 1
     * @maxItems 32
     */
    rules?: [UiStatusRule, ...(UiStatusRule)[]];
}
interface UiStatusRule {
    /**
     * The value is a number, or text that is one, below this.
     */
    lt?: number;
    /**
     * The value is a number, or text that is one, at most this.
     */
    lte?: number;
    /**
     * The value is a number, or text that is one, above this.
     */
    gt?: number;
    /**
     * The value is a number, or text that is one, at least this.
     */
    gte?: number;
    /**
     * The value equals this, either way round: as numbers when either is a number and both read as one (0 matches "0.0", "404" matches 404), else as text (true matches "true").
     */
    eq?: (string | number | boolean);
    tone: UiTone1;
}

type FreshnessState = "fresh" | "stale" | "unreachable" | "static" | "pending";
interface FreshnessStamp {
    state: FreshnessState;
    observedAt: string | null;
    ageMs: number | null;
    ttlMs: number | null;
}
/**
 * One widget's `select` over the envelope's data, evaluated on the server: the value (plain
 * JSON; `null` where the expression selects nothing), or why the expression failed on this
 * data.
 */
type ProviderProjection = {
    value: JsonValue$1;
} | {
    error: string;
};
interface ProviderEnvelope<T = unknown> {
    id: string;
    kind: string;
    freshness: FreshnessStamp;
    data: T | null;
    error: {
        message: string;
    } | null;
    /**
     * The `select` of each widget that reads this provider, over `data`, by the widget's id
     * (`widget:ui/<page>.<name>`). Absent when no widget selects from it, and empty while there
     * is no data. An older server never sends it.
     */
    projections?: Readonly<Record<string, ProviderProjection>>;
}

type DeckConfig = DeckConfigDocument;

type ConfigState = {
    status: "loading";
} | {
    status: "ready";
    config: DeckConfig;
} | {
    status: "error";
    message: string;
};
/**
 * The estate config. Every caller shares one `/api/config` request per page load. A failed
 * read is not cached: it is asked again every poll interval until it succeeds (as the
 * per-feature pollers did), and on the next mount (a Retry that remounts its loader).
 */
declare function useConfig(): ConfigState;
type UiManifestState = {
    status: "loading";
} | {
    status: "ready";
    manifest: UiManifest;
} | {
    status: "error";
    message: string;
};
/**
 * The resolved UI manifest (`/api/ui`), shared by every reader: one read per page load, then
 * again when the window regains focus (or the page becomes visible) and every
 * {@link UI_MANIFEST_REFRESH_MS}, so a `ui` config change shows without a reload (an unchanged
 * manifest keeps its references). Once read, a failed re-read keeps it. When it cannot be read
 * at all the state is `error` (a settled answer), asked again every poll interval until it
 * succeeds; it never goes back to `loading` while it is asked again.
 */
declare function useUiManifest(): UiManifestState;
/** A provider by id, or the provider of a kind (the first by id when several share it). */
type ProviderRef = string | {
    kind: string;
};
interface ProviderState<T> {
    /** The latest envelope, or `null` when the provider is not configured or unreadable. */
    envelope: ProviderEnvelope<T> | null;
    /** True until the first read settles (or it is known not to be configured). */
    loading: boolean;
}
/**
 * Poll one provider's envelope every `intervalMs` (the shell default). Every caller of the
 * same provider shares one request per tick, wherever it is mounted; a caller that joins
 * within an interval of the last read reuses it. Without a manifest every provider is polled
 * (the manifest query leaves the warning).
 */
declare function useProvider<T>(ref: ProviderRef, options?: {
    intervalMs?: number;
}): ProviderState<T>;
interface ProvidersState<T> {
    /** Each asked provider's latest envelope, by id; `null` when it is not configured or unreadable. */
    envelopes: ReadonlyMap<string, ProviderEnvelope<T> | null>;
    /** True until every read settles (or each is known not to be configured). */
    loading: boolean;
    /** The asked providers whose first read has not settled yet (all of them while the manifest loads). */
    pending: ReadonlySet<string>;
}
/**
 * Poll several providers by id, as {@link useProvider} polls one: the same shared query per
 * provider, so a page and a pill reading one provider make one request per tick. Unlisted
 * providers are not polled. The ids may change between renders.
 */
declare function useProviders<T>(ids: readonly string[], options?: {
    intervalMs?: number;
}): ProvidersState<T>;

/**
 * The curated icon set: every icon deck renders, keyed by the string token that
 * estate config, `registerPage` and feature state maps use.
 *
 * Import each Lucide icon by name here and nowhere else. Never use
 * `lucide-react/dynamic` or a namespace import: either one ships the whole set.
 *
 * Aliases (`check-circle` ≡ `circle-check`, Lucide's older names, and the
 * literal unicode glyphs legacy state maps still use) resolve to the same
 * component, so existing tokens keep working while features migrate.
 */

declare const ICONS: {
    readonly "circle-check": LucideIcon;
    readonly "check-circle": LucideIcon;
    readonly "database-check": LucideIcon;
    readonly "circle-x": LucideIcon;
    readonly "x-circle": LucideIcon;
    readonly "circle-minus": LucideIcon;
    readonly "minus-circle": LucideIcon;
    readonly minus: LucideIcon;
    readonly "circle-help": LucideIcon;
    readonly "circle-question-mark": LucideIcon;
    readonly slash: LucideIcon;
    readonly "circle-slash": LucideIcon;
    readonly "circle-stop": LucideIcon;
    readonly "circle-dashed": LucideIcon;
    readonly "triangle-alert": LucideIcon;
    readonly "alert-triangle": LucideIcon;
    readonly "octagon-alert": LucideIcon;
    readonly "alert-octagon": LucideIcon;
    readonly "clock-alert": LucideIcon;
    readonly hourglass: LucideIcon;
    readonly "calendar-clock": LucideIcon;
    readonly ban: LucideIcon;
    readonly info: LucideIcon;
    readonly circle: LucideIcon;
    readonly inbox: LucideIcon;
    readonly "database-off": LucideIcon;
    readonly "database-x": LucideIcon;
    readonly "cloud-off": LucideIcon;
    readonly link: LucideIcon;
    readonly "link-off": LucideIcon;
    readonly unlink: LucideIcon;
    readonly file: LucideIcon;
    readonly "file-digit": LucideIcon;
    readonly "file-binary": LucideIcon;
    readonly "file-question": LucideIcon;
    readonly "file-question-mark": LucideIcon;
    readonly folder: LucideIcon;
    readonly "folder-open": LucideIcon;
    readonly "external-link": LucideIcon;
    readonly "search-x": LucideIcon;
    readonly play: LucideIcon;
    readonly "circle-play": LucideIcon;
    readonly "play-circle": LucideIcon;
    readonly archive: LucideIcon;
    readonly "eye-off": LucideIcon;
    readonly "power-off": LucideIcon;
    readonly x: LucideIcon;
    readonly "chevron-right": LucideIcon;
    readonly "chevron-down": LucideIcon;
    readonly copy: LucideIcon;
    readonly check: LucideIcon;
    readonly "refresh-cw": LucideIcon;
    readonly "layout-grid": LucideIcon;
    readonly server: LucideIcon;
    readonly boxes: LucideIcon;
    readonly "git-compare": LucideIcon;
    readonly activity: LucideIcon;
    readonly zap: LucideIcon;
    readonly "book-open": LucideIcon;
    readonly "file-cog": LucideIcon;
    readonly house: LucideIcon;
    readonly monitor: LucideIcon;
    readonly gauge: LucideIcon;
    readonly sun: LucideIcon;
    readonly moon: LucideIcon;
    readonly "sun-moon": LucideIcon;
    readonly search: LucideIcon;
    readonly "circle-plus": LucideIcon;
    readonly "plus-circle": LucideIcon;
    readonly "\u2713": LucideIcon;
    readonly "\u2715": LucideIcon;
    readonly "\u25B2": LucideIcon;
    readonly "\u26A0": LucideIcon;
    readonly "\u25C6": LucideIcon;
    readonly "\u25CB": LucideIcon;
    readonly "\u25D0": LucideIcon;
    readonly "\u25D4": LucideIcon;
    readonly "\u2205": LucideIcon;
    readonly ℹ: LucideIcon;
    readonly "\u2600": LucideIcon;
    readonly "\u263E": LucideIcon;
};
type IconName = keyof typeof ICONS;

interface IconProps extends Omit<LucideProps, "ref"> {
    /** A curated `IconName`, a module's contributed icon (`<module>/<name>`), or a config-supplied token that may be neither. */
    name: IconName | (string & {});
    /** Pixel size; defaults to 16. */
    size?: number;
}
/**
 * A decorative icon from the curated set, or one a module contributes as SVG (sanitised; see
 * `contributed-icons.ts`). Always `aria-hidden`: the adjacent text is the accessible label,
 * so an icon is never the only signal. An unknown token renders a neutral circle (and warns
 * once in development) rather than an empty box or the raw token text.
 */
declare function Icon({ name, size, ...props }: IconProps): React.JSX.Element;

/**
 * One wording for times across deck: "just now", "42s ago", "6m ago", "3h ago",
 * "8d ago". Pure functions; callers pass `now` so rendering stays deterministic.
 */
/** Age in milliseconds → "6m ago". Negative ages (clock skew) read as "just now". */
declare function formatAge(ageMs: number): string;
/** An ISO timestamp relative to `now` (epoch ms or Date). Unparseable input is returned as-is. */
declare function formatRelative(iso: string, now?: number | Date): string;
/** An ISO timestamp as local "2026-01-15 12:00". Unparseable input is returned as-is. */
declare function formatTimestamp(iso: string): string;

/** The six status tones. Each maps to `--status-{tone}-fg/-bg/-border` in theme.css. */
type Tone = "ok" | "warn" | "danger" | "info" | "pending" | "neutral";
declare const TONES: readonly Tone[];
/**
 * The icon a bare tone shows, for a state that has a tone but no map entry of a feature's own
 * (a config-declared status map's): so a toned value still never relies on colour alone.
 */
declare const TONE_ICON: Readonly<Record<Tone, IconName>>;
/** How one state of a domain value presents: tone and icon, plus text so colour is never alone. */
interface StatusPresentation {
    tone: Tone;
    icon: IconName;
    label: string;
    /** Live-region role when the state should be announced; omit for static text. */
    role?: "status" | "alert";
}
type StatusMap<S extends string> = Readonly<Record<S, StatusPresentation>>;
/**
 * Declare a feature's state → presentation map. The identity function exists for
 * the type: every state must be covered, and every icon must be a curated name.
 * Maps stay feature-owned (their contrast/a11y tests import them).
 */
declare function defineStatusMap<S extends string>(map: Record<S, StatusPresentation>): StatusMap<S>;

/** One breadcrumb step; the last one is the current page and takes no `href`. */
interface BreadcrumbEntry {
    label: string;
    href?: string;
}
interface PageHeaderProps {
    /** The page title, rendered as the page's single heading. */
    title: ReactNode;
    /**
     * The heading id. Defaults to one derived from a string `title`
     * (`usePageHeadingId(title)`), or a generated one for a ReactNode title.
     */
    id?: string;
    description?: ReactNode;
    /** Trailing status slot beside the title (FreshnessBadge, StatusBadge, …). */
    meta?: ReactNode;
    /** Page-level actions, right-aligned (wrap below on narrow screens). */
    actions?: ReactNode;
    /** Breadcrumb trail above the title: entries, or a composed `Breadcrumb`. */
    breadcrumbs?: readonly BreadcrumbEntry[] | ReactNode;
    /**
     * Heading level. Pages leave it at 1 (the single `h1`); a non-page context
     * (the `/_ui` workbench, a dialog) may demote it so it doesn't compete with
     * the real page heading.
     */
    level?: 1 | 2 | 3;
    className?: string;
}
/**
 * The top of a page: optional breadcrumbs, the page heading with a stable id,
 * a `meta` status slot, a description and right-aligned actions. It renders the
 * heading, not the surrounding `section`: the page wraps it in
 * `<section aria-labelledby={usePageHeadingId(title)}>`.
 */
declare function PageHeader({ title, id, description, meta, actions, breadcrumbs, level, className, }: PageHeaderProps): React.JSX.Element;

interface SectionProps extends Omit<ComponentProps<"section">, "title" | "aria-labelledby"> {
    /** The section heading. */
    title: ReactNode;
    /** The section element's id (an in-page anchor). The heading id becomes `{id}-heading`. */
    id?: string;
    /** Override the heading id outright (e.g. to keep an id existing links target). */
    headingId?: string;
    description?: ReactNode;
    /** Section-level actions, right of the heading. */
    actions?: ReactNode;
    /** `plain` (default) flows in the page; `card` sits on a bordered card surface. */
    variant?: "plain" | "card";
    /** Heading level: 2 (default) under the page `h1`, 3 to 5 for nested sections. */
    level?: 2 | 3 | 4 | 5;
}
/**
 * A titled region of a page: `section[aria-labelledby]` named by its own
 * heading, with an optional description and actions row.
 */
declare function Section({ title, id, headingId, description, actions, variant, level, className, children, ...props }: SectionProps): React.JSX.Element;

interface EmptyStateProps {
    /** What is empty ("No documents to show"). */
    title: ReactNode;
    description?: ReactNode;
    /** A neutral glyph; defaults to `inbox`. Never a failure glyph — that is ErrorState. */
    icon?: IconName;
    /** A next step (a link or button). */
    action?: ReactNode;
    /** One-line variant for in-table / in-list use (e.g. a DataTable's empty row). */
    compact?: boolean;
    className?: string;
}
/**
 * "Acquired, nothing to show": a polite `role="status"` region with a neutral
 * icon + text. Deliberately distinct in role, glyph and tone from `ErrorState`.
 */
declare function EmptyState({ title, description, icon, action, compact, className }: EmptyStateProps): React.JSX.Element;

interface ErrorStateProps {
    /** What failed ("This source could not be loaded"). */
    title: ReactNode;
    /** A safe, user-facing explanation. Never raw exception text or stack traces. */
    message?: ReactNode;
    /** Shows a Retry button that calls this. */
    onRetry?: () => void;
    /** Accessible name / text of the retry button. */
    retryLabel?: string;
    /** Extra diagnostic detail, collapsed behind a "Details" disclosure. */
    details?: ReactNode;
    /** Tighter variant for in-table / in-list / fragment use. */
    compact?: boolean;
    className?: string;
}
/**
 * An explicit failure region: `role="alert"`, a failure glyph + text, and an
 * optional Retry. Distinct in role, glyph and tone from `EmptyState`.
 */
declare function ErrorState({ title, message, onRetry, retryLabel, details, compact, className, }: ErrorStateProps): React.JSX.Element;

type LoadingPreset = "lines" | "table" | "cards" | "detail";
interface LoadingStateProps {
    /** What is loading; the region's accessible name and visible text. */
    label?: string;
    /** Skeleton shape approximating the content that will replace it. */
    preset?: LoadingPreset;
    /** Row / line / card count for the preset (defaults: lines 3, table 5, cards 3, detail 4). */
    rows?: number;
    /** Keep the label for assistive tech only (visually hidden). */
    hideLabel?: boolean;
    className?: string;
}
/**
 * A loading placeholder: `role="status"` + `aria-busy`, named by its visible
 * "Loading…" text. The skeleton shapes are decorative (`aria-hidden`).
 */
declare function LoadingState({ label, preset, rows, hideLabel, className, }: LoadingStateProps): React.JSX.Element;

type CalloutRole = "alert" | "status" | "note";
interface CalloutProps extends Omit<ComponentProps<"div">, "title" | "role"> {
    tone?: Tone;
    title?: ReactNode;
    /** Body text. */
    children?: ReactNode;
    /** Overrides the tone's default icon. */
    icon?: IconName;
    /** A follow-up affordance (link or button) under the body. */
    action?: ReactNode;
    /**
     * Shows a dismiss button. Dismissal state is caller-owned: the callout never
     * hides itself or persists anything — the caller stops rendering it.
     */
    onDismiss?: () => void;
    /** Accessible name of the dismiss button. */
    dismissLabel?: string;
    /** Overrides the tone-derived role (see `calloutRole`). */
    role?: CalloutRole;
    /** Tighter padding for inline / fragment use. */
    compact?: boolean;
}
/**
 * A toned notice on shadcn's `Alert`: icon + text (never colour alone), a role
 * derived from the tone, an optional action and a caller-owned dismiss.
 */
declare function Callout({ tone, title, children, icon, action, onDismiss, dismissLabel, role, compact, className, ...props }: CalloutProps): React.JSX.Element;

interface FragmentBoundaryProps {
    /** The isolated fragment (a slot fragment, header summary, evidence field …). */
    children: ReactNode;
    /** Fixed, caller-chosen name of the fragment ("Alerts summary"); the fallback reads "{label} unavailable". */
    label: string;
    /** Keeps the fragment's navigation working in the fallback (renders the text as a link). */
    href?: string;
    /** Replaces the default compact callout entirely. */
    fallback?: ReactNode;
    /** When this value changes, a prior failure is cleared. */
    resetKey?: unknown;
    /** Diagnostic hook, called from `componentDidCatch`. */
    onError?: (error: unknown) => void;
}
interface FragmentBoundaryState {
    failed: boolean;
    /** Failed, and a reset key change asked for another try: the fragment renders beside the fallback. */
    retrying: boolean;
    /** Retries so far, keying a fresh retry boundary each time. */
    attempt: number;
    lastResetKey: unknown;
}
/**
 * Inline render isolation for a fragment inside a host page. A throw renders a
 * compact danger `Callout` (`role="alert"`) with fixed text — never the caught
 * exception — so the host page and sibling fragments keep working. On success it
 * renders the children with no wrapper element.
 *
 * A `resetKey` change retries a failed fragment without re-announcing it: the fragment is
 * tried beside the still-mounted fallback, inside its own nested boundary, so a retry that
 * fails again leaves this boundary's fallback node in place (no new alert), and one that
 * succeeds drops the fallback before paint. A failure is logged and reported once per
 * episode, not once per retry.
 */
declare class FragmentBoundary extends Component<FragmentBoundaryProps, FragmentBoundaryState> {
    state: FragmentBoundaryState;
    /** Whether the current failure episode has been logged. */
    private reported;
    static getDerivedStateFromError(): Partial<FragmentBoundaryState>;
    static getDerivedStateFromProps(props: FragmentBoundaryProps, state: FragmentBoundaryState): Partial<FragmentBoundaryState> | null;
    componentDidCatch(error: unknown): void;
    /** Log and report a failure, once per episode. */
    private report;
    /** The retry threw again: the episode goes on, with the same fallback. */
    private readonly retryFailed;
    /** The retried fragment rendered and committed: the episode is over. */
    private readonly recovered;
    private renderFallback;
    render(): ReactNode;
}

type KeyValueLayout = "stacked" | "inline" | "grid";
interface KeyValueItem {
    /** React key; defaults to the label when it is a string, else the index. */
    id?: string;
    label: ReactNode;
    value: ReactNode;
    /** Secondary text under the value (provenance, units, a short explanation). */
    hint?: ReactNode;
}
interface KeyValueListProps extends Omit<ComponentProps<"dl">, "children"> {
    /** Pairs to render. Use `children` (`<KeyValue>`) instead for custom groups. */
    items?: readonly KeyValueItem[];
    children?: ReactNode;
    /**
     * - `grid` (default): two columns, label ▸ value, collapsing to stacked pairs on narrow screens.
     * - `stacked`: label above value, one pair per row.
     * - `inline`: compact pairs flowing along one line (meta rows).
     */
    layout?: KeyValueLayout;
}
/**
 * Label/value pairs as a description list: a `dl` whose pairs are each wrapped in a
 * `div` group (valid HTML, and screen readers announce "term, definition").
 */
declare function KeyValueList({ items, children, layout, className, ...props }: KeyValueListProps): React.JSX.Element;
interface KeyValueProps extends Omit<ComponentProps<"div">, "children"> {
    label: ReactNode;
    /** The value; `children` is an alias for richer content. */
    value?: ReactNode;
    children?: ReactNode;
    hint?: ReactNode;
}
/** One `dt`/`dd` pair inside a {@link KeyValueList}. */
declare function KeyValue({ label, value, children, hint, className, ...props }: KeyValueProps): React.JSX.Element;

interface StatTileProps {
    label: ReactNode;
    /** The headline number (or short value). Rendered large, in tabular figures. */
    value: ReactNode;
    /** Tints the value and the tile's leading edge. The label carries the meaning. */
    tone?: Tone;
    icon?: IconName;
    subLabel?: ReactNode;
    /** Makes the whole tile a link. */
    href?: string;
    /** Link component for `href` (e.g. the router's link); defaults to `<a>`. */
    linkAs?: ElementType<{
        href: string;
        className?: string;
        children?: ReactNode;
    }>;
    className?: string;
}
/** One headline number with its label: a single-pair `dl`, optionally a link. */
declare function StatTile({ label, value, tone, icon, subLabel, href, linkAs: LinkAs, className, }: StatTileProps): React.JSX.Element;
/** Auto-fitting grid of {@link StatTile}s. */
declare function StatGrid({ className, ...props }: ComponentProps<"div">): React.JSX.Element;

interface MeterProps {
    /** Names the meter. */
    label: ReactNode;
    /** The measured value, clamped to `0..max`. */
    value: number;
    max?: number;
    /** Tints the fill and the value text. Always pair a non-neutral tone with `icon`. */
    tone?: Tone;
    /** Shown before the value, so the tone is never carried by colour alone. */
    icon?: IconName;
    /** Visible value text; defaults to the rounded percentage of `max`. */
    valueText?: string;
    /** Screen-reader value wording (`aria-valuetext`), e.g. "82% used, nearing limit". Defaults to `valueText`. */
    srValueText?: string;
    /** Secondary line under the bar, e.g. a reset countdown or source attribution. */
    meta?: ReactNode;
    className?: string;
}
/**
 * A labelled horizontal gauge (`role="meter"`) for a bounded quantity such as
 * quota used. The value is text as well as geometry; the fill width is the only
 * inline style.
 */
declare function Meter({ label, value, max, tone, icon, valueText, srValueText, meta, className, }: MeterProps): React.JSX.Element;

interface CodeBlockProps {
    /** The source text. Always what the copy button copies. */
    code: string;
    /**
     * Pre-highlighted markup for `code`, e.g. highlight.js output. It is injected as
     * HTML, so it must be escaped token markup (highlight.js escapes its input) —
     * never raw user HTML. Omit it to render `code` as plain text.
     */
    highlightedHtml?: string;
    /** Language token; shown in the toolbar and set as `language-*` on the `code` element. */
    language?: string;
    /** Visible caption (file name, command, …); becomes the figure's accessible name. */
    caption?: ReactNode;
    /** Show the copy button (default true). */
    copy?: boolean;
    /** Soft-wrap long lines instead of scrolling horizontally. */
    wrap?: boolean;
    /** Cap the block's height (CSS length or px) and scroll beyond it. */
    maxHeight?: string | number;
    className?: string;
}
/**
 * A `figure` holding a code listing, with an optional `figcaption`, a language
 * label and a copy button. Token colours come from `styles/hljs.css`, mapped to
 * theme tokens for light and dark. The scrolling `pre` is keyboard-focusable.
 */
declare function CodeBlock({ code, highlightedHtml, language, caption, copy, wrap, maxHeight, className, }: CodeBlockProps): React.JSX.Element;

interface ProseProps extends Omit<ComponentProps<"div">, "children" | "dangerouslySetInnerHTML"> {
    /**
     * Rendered HTML that the caller has ALREADY sanitized (e.g. markdown through
     * DOMPurify). This component does not sanitize: never pass untrusted HTML.
     */
    sanitizedHtml: string;
}
/**
 * Long-form rendered content (markdown documents) styled by
 * `@tailwindcss/typography`, with its palette mapped to theme tokens. Fenced
 * code inside picks up the highlight.js token theme.
 */
declare function Prose({ sanitizedHtml, className, ...props }: ProseProps): React.JSX.Element;

interface DisclosureProps {
    /** Trigger text; it names the button. */
    label: ReactNode;
    /** Optional count shown after the label (e.g. hidden items), in tabular figures. */
    count?: number;
    children: ReactNode;
    defaultOpen?: boolean;
    /** Controlled open state (pair with `onOpenChange`). */
    open?: boolean;
    onOpenChange?: (open: boolean) => void;
    /**
     * When the panel collapses while focus is inside it (e.g. a "Done" button in
     * the panel, or a programmatic close), move focus back to the trigger instead
     * of losing it to the page. Default true.
     */
    refocusOnCollapse?: boolean;
    className?: string;
    contentClassName?: string;
}
/**
 * A collapsible section with a consistent trigger: a chevron, the label and an
 * optional count. The trigger is a real button with `aria-expanded` and
 * `aria-controls` (Radix Collapsible).
 */
declare function Disclosure({ label, count, children, defaultOpen, open: openProp, onOpenChange, refocusOnCollapse, className, contentClassName, }: DisclosureProps): React.JSX.Element;

type VisuallyHiddenProps = Omit<ComponentProps<"span">, "ref"> & {
    /** Render as a block element, e.g. for a live region that holds a sentence. */
    as?: "span" | "div" | "p";
};
/**
 * Text for assistive technology only (Tailwind `sr-only`). Use it for live
 * regions (`aria-live`), extra link context ("(opens in new tab)") and any label
 * whose visible form is an icon. Plain `className="sr-only"` is fine for one-offs.
 */
declare function VisuallyHidden({ as: Tag, className, ...props }: VisuallyHiddenProps): React.JSX.Element;

type SafeRouteLinkProps = Omit<ComponentProps<"a">, "href" | "children"> & {
    /**
     * Builds the in-app href, typically `encodeURIComponent`-ing route params. A
     * param that cannot be encoded (e.g. a lone surrogate) throws `URIError`.
     */
    build: () => string;
    children: ReactNode;
    /** Shown instead of the link when `build` throws `URIError`. */
    fallback?: ReactNode;
};
/**
 * An in-app route link whose href is built defensively. When `build` throws
 * `URIError`, it renders a non-interactive "Invalid entity link" marker (icon +
 * text) instead of a raw unsafe href, and the surrounding page keeps rendering.
 * Any other error is a bug and propagates to the nearest error boundary.
 *
 * It renders a plain `<a href>`: the shell routes same-origin anchor clicks
 * client-side, so the library stays independent of the router.
 */
declare function SafeRouteLink({ build, children, fallback, className, ...props }: SafeRouteLinkProps): React.JSX.Element;

type ExternalLinkProps = Omit<ComponentProps<"a">, "target" | "rel"> & {
    href: string;
    /** Show the trailing external-link glyph (default true). The sr text is always present. */
    showIcon?: boolean;
    /**
     * Leave out the inline text-link look, for an anchor its host styles (a sidebar menu button
     * rendering it `asChild`). The new-tab semantics, glyph and sr text stay.
     */
    plain?: boolean;
};
/**
 * A link that opens in a new tab: `target="_blank" rel="noopener noreferrer"`,
 * a trailing external glyph, and a visually hidden "(opens in new tab)" so the
 * accessible name warns about the context change.
 */
declare function ExternalLink({ children, showIcon, plain, className, ...props }: ExternalLinkProps): React.JSX.Element;

type StatusBadgeSize = "sm" | "md";
/** `soft` = tinted pill; `outline` = bordered, no fill; `dot` = tinted icon beside plain text. */
type StatusBadgeVariant = "soft" | "outline" | "dot";
interface StatusBadgeProps extends Omit<ComponentProps<"span">, "title" | "children" | "role"> {
    tone: Tone;
    icon: IconName | (string & {});
    label: ReactNode;
    /** Muted suffix after a separator, e.g. "as of 58s ago". Part of the accessible text. */
    detail?: ReactNode;
    size?: StatusBadgeSize;
    variant?: StatusBadgeVariant;
    /**
     * Supplementary tooltip (e.g. the full observation time). It must never be the
     * only carrier of information. When set, the badge becomes focusable so the
     * tooltip is reachable by keyboard too.
     */
    title?: ReactNode;
    /** Live-region role when a change should be announced; omit for static text. */
    role?: "status" | "alert";
}
/**
 * A status as icon + text, never colour alone. Tone picks token colours only;
 * the label carries the meaning. `detail` renders a muted "· …" suffix.
 */
declare function StatusBadgeBase({ tone, icon, label, detail, size, variant, title, className, ...props }: StatusBadgeProps): React.JSX.Element;
/** Extra props when binding a map entry: everything but the presentation itself. */
type StatusBadgeMapProps = Omit<StatusBadgeProps, "tone" | "icon" | "label"> & Partial<Pick<StatusBadgeProps, "label">>;
/** Bind a feature's `defineStatusMap` entry to a badge: `StatusBadge.fromMap(MAP, state)`. */
declare function fromMap<S extends string>(map: StatusMap<S>, state: S, props?: StatusBadgeMapProps): ReactElement;
declare const StatusBadge: typeof StatusBadgeBase & {
    fromMap: typeof fromMap;
};

interface RelativeTimeProps extends Omit<ComponentProps<"time">, "dateTime" | "children"> {
    /** An ISO timestamp. Unparseable input renders verbatim, without a tooltip. */
    value: string;
    /**
     * The reference time. Pass it for deterministic output (tests, the workbench,
     * or a parent that already ticks); omit it and the text re-reads the clock
     * every `tickMs`.
     */
    now?: number | Date;
    tickMs?: number;
    /** Show the absolute local time in a hover tooltip (default true). */
    tooltip?: boolean;
}
/**
 * `<time dateTime>` with relative text ("6m ago"). The machine-readable instant
 * is always in `dateTime`; the absolute local time is a supplementary tooltip.
 */
declare function RelativeTime({ value, now, tickMs, tooltip, className, ...props }: RelativeTimeProps): React.JSX.Element;

interface FreshnessBadgeProps extends StatusBadgeMapProps {
    freshness: FreshnessStamp;
    /**
     * Reference time for a deterministic age (`now − observedAt`). Omit it and the
     * age is the server's `ageMs` plus the time since this stamp arrived, re-read
     * every `tickMs`.
     */
    now?: number | Date;
    tickMs?: number;
    /** Show `freshnessTitle` as a tooltip (default true). Turn off inside a link. */
    tooltip?: boolean;
}
/**
 * `StatusBadge` bound to a provider `FreshnessStamp`: "Fresh · as of 6m ago".
 * Static links and pending stamps show no age. The age ticks unless `now` is given.
 */
declare function FreshnessBadge({ freshness, now, tickMs, tooltip, ...props }: FreshnessBadgeProps): React.JSX.Element;

interface HealthPillProps extends Omit<ComponentProps<"a">, "href" | "children" | "title"> {
    tone: Tone;
    icon: IconName | (string & {});
    /** Short visible text; truncates in narrow headers (the tooltip shows it in full). */
    label: string;
    /** The owning page. */
    href: string;
    /** Optional count shown as a tabular badge after the label; a string carries its unit, e.g. "82%". */
    count?: number | string;
    /** Screen-reader wording for the count, e.g. "3 active findings". Defaults to the number. */
    countLabel?: string;
    /** Trailing content inside the link, e.g. a `FreshnessBadge` with `tooltip={false}`. */
    meta?: ReactNode;
    /** Tooltip text; defaults to the label (and count), so truncated text stays readable. */
    title?: ReactNode;
}
/**
 * A compact header link summarising one area's health: tone-tinted icon + short
 * text + optional count, pointing at the page that owns the detail. The whole
 * pill is one link; its accessible name is the label plus the count.
 */
declare function HealthPill({ tone, icon, label, href, count, countLabel, meta, title, className, ...props }: HealthPillProps): React.JSX.Element;

declare module "@tanstack/react-table" {
    interface ColumnMeta<TData extends RowData, TValue> {
        /** Classes for this column's body cells. */
        className?: string;
        /** Classes for this column's header cell. */
        headerClassName?: string;
        /** `"end"` right-aligns (numbers). */
        align?: "start" | "end";
    }
}
type LinkComponent$2 = ElementType<{
    href: string;
    className?: string;
    children?: ReactNode;
}>;
interface DataTableProps<T> {
    /**
     * TanStack column defs. A def with `columns: [...]` is a group: it renders a
     * two-row header, with the group cell `scope="colgroup"` spanning its leaves.
     * A `cell` renderer is called as a function (no hooks inside it).
     */
    columns: ColumnDef<T, any>[];
    data: readonly T[];
    /** The table's caption; it also names the scroll region. */
    caption: ReactNode;
    /** Keep the caption for assistive tech but hide it visually. */
    captionHidden?: boolean;
    /** Stable row key (TanStack row id): React key and `data-row-link` value. */
    getRowId: (row: T, index: number) => string;
    /** Makes the first cell's content a link to this href (`data-row-link` = row id). */
    rowLink?: (row: T) => string | undefined;
    /** Link component for `rowLink` (e.g. the router's link); defaults to `<a>`. */
    linkAs?: LinkComponent$2;
    /** DOM `id` for a row (plus `tabIndex=-1`), so a hash or a script can focus it. */
    rowDomId?: (row: T) => string;
    /** The first column's cells are row headers (`th scope="row"`). Default `true`. */
    rowHeader?: boolean;
    /** Shown in one full-width row when `data` is empty: a title, or full EmptyState props. */
    empty?: ReactNode | Omit<EmptyStateProps, "compact">;
    /** `compact` (default, D16: compact tables) or `comfortable`. */
    density?: "comfortable" | "compact";
    /** Header cells stick to the top of the scroll region (bound its height via `className`). Default `true`. */
    stickyHeader?: boolean;
    /** Classes for the scroll region (the root), e.g. `max-h-96` for a sticky header. */
    className?: string;
}
/**
 * A data table over TanStack Table (headless) and the shadcn table primitives.
 * It owns the caption, grouped headers with `scope`, row headers, the row-link
 * convention, the empty row and horizontal scrolling in a focusable, labelled
 * region. Figures are tabular (`tabular-nums`).
 */
declare function DataTable<T>({ columns, data, caption, captionHidden, getRowId, rowLink, linkAs: LinkAs, rowDomId, rowHeader, empty, density, stickyHeader, className, }: DataTableProps<T>): React.JSX.Element;

type ListVariant = "plain" | "divided" | "card";
interface ListProps {
    as?: "ul" | "ol";
    /** `plain` (spaced rows), `divided` (rules between rows) or `card` (each row a bordered card). */
    variant?: ListVariant;
    "aria-label"?: string;
    "aria-labelledby"?: string;
    id?: string;
    className?: string;
    children?: ReactNode;
}
/** A semantic list of {@link ListItem}s. */
declare function List({ as: Tag, variant, className, children, ...props }: ListProps): React.JSX.Element;
type LinkComponent$1 = ElementType<{
    href: string;
    className?: string;
    children?: ReactNode;
}>;
type CurrentValue = "true" | "page" | "location" | "step";
interface ListItemProps {
    /** A leading glyph or badge (decorative, or text-bearing like a status badge). */
    leading?: ReactNode;
    title: ReactNode;
    description?: ReactNode;
    /** Trailing, secondary facts (a time, a count). Not interactive. */
    meta?: ReactNode;
    /** Row actions (buttons, links). They stay separately focusable beside the row link. */
    actions?: ReactNode;
    /** Whole-row link. The title is the link; its hit area stretches over the row. */
    href?: string;
    /** Link component for `href` (e.g. the router's link); defaults to `<a>`. */
    linkAs?: LinkComponent$1;
    /** Whole-row button (mutually exclusive with `href`). */
    onSelect?: () => void;
    /** The current row: `aria-current` (on the link/button, else the row) + a highlight. */
    selected?: boolean;
    /** The `aria-current` token used when `selected`. Default `"true"`; `"page"` for nav links. */
    current?: CurrentValue;
    /** Programmatic focus target (e.g. a hash). Use `tabIndex={-1}` with it. */
    id?: string;
    tabIndex?: number;
    className?: string;
    /** Extra content below the description (e.g. a nested detail). */
    children?: ReactNode;
}
/**
 * One list row: `leading` · title/description · `meta` · `actions`.
 *
 * Interaction modes:
 * - static (default);
 * - `href`: the title is one link whose hit area covers the row (stretched
 *   `::after`), so actions stay real, separate controls, never nested inside it;
 * - `onSelect`: the same, with a button.
 */
declare function ListItem({ leading, title, description, meta, actions, href, linkAs: LinkAs, onSelect, selected, current, id, tabIndex, className, children, }: ListItemProps): React.JSX.Element;
interface ListGroupProps {
    heading: ReactNode;
    /** Heading level: 2 (default), 3 or 4. */
    level?: 2 | 3 | 4;
    /** Item count shown beside the heading. */
    count?: number;
    description?: ReactNode;
    id?: string;
    className?: string;
    /** The group's {@link List}. */
    children?: ReactNode;
}
/** A headed group of rows: `section[aria-labelledby]` with a heading, an optional count and a List. */
declare function ListGroup({ heading, level, count, description, id, className, children }: ListGroupProps): React.JSX.Element;

type LinkComponent = ElementType<{
    href: string;
    className?: string;
    children?: ReactNode;
}>;
interface LinkTileProps {
    title: ReactNode;
    description?: ReactNode;
    /** A curated icon name, or any decorative node (e.g. a service logo). */
    icon?: IconName | ReactNode;
    /** Top-right status (e.g. a StatusBadge). Must not be interactive. */
    status?: ReactNode;
    /** Footer facts (e.g. a FreshnessBadge). Must not be interactive. */
    meta?: ReactNode;
    /** The destination. Without it (or with `disabled`) the tile is a non-interactive `article`. */
    href?: string;
    /** Opens in a new tab (`target=_blank`, `rel=noopener noreferrer`), with an icon and an sr-only note. */
    external?: boolean;
    /** Link component for internal links (e.g. the router's link); defaults to `<a>`. */
    linkAs?: LinkComponent;
    /** Renders the tile inert and muted: no link, nothing focusable. */
    disabled?: boolean;
    /** Why the tile is disabled; shown in place of `description`'s footer slot. */
    disabledReason?: ReactNode;
    className?: string;
}
/**
 * A whole-card link: a single `<a>` wrapping icon, title, description, status
 * and meta, so there is exactly one tab stop and nothing interactive nested
 * inside. Disabled tiles are a plain `article` (no fake focusable element).
 */
declare function LinkTile({ title, description, icon, status, meta, href, external, linkAs: LinkAs, disabled, disabledReason, className, }: LinkTileProps): React.JSX.Element;

interface CardGridProps {
    /** Optional group heading; the grid becomes a `section` named by it. */
    heading?: ReactNode;
    /** Heading level: 2 (default) to 5. */
    level?: 2 | 3 | 4 | 5;
    /** Item count shown beside the heading. */
    count?: number;
    description?: ReactNode;
    /** Names the list when there is no heading. */
    "aria-label"?: string;
    /**
     * 2-D arrow-key navigation between items' focusable elements (←/→ within a
     * row, ↑/↓ by row, Home/End), measured from the live layout.
     */
    navigable?: boolean;
    id?: string;
    className?: string;
    /** One card per child (e.g. `LinkTile`s); each is wrapped in a list item. */
    children?: ReactNode;
}
/** A responsive auto-fill grid of cards (`minmax(16rem, 1fr)`), as a list, with an optional heading. */
declare function CardGrid({ heading, level, count, description, navigable, id, className, children, ...labelling }: CardGridProps): React.JSX.Element;

export { Callout, CardGrid, CodeBlock, DECK_API_VERSION, DataTable, Disclosure, EmptyState, ErrorState, ExternalLink, FragmentBoundary, FreshnessBadge, HealthPill, Icon, KeyValue, KeyValueList, LinkTile, List, ListGroup, ListItem, LoadingState, Meter, PageHeader, Prose, RelativeTime, SafeRouteLink, Section, StatGrid, StatTile, StatusBadge, TONES, TONE_ICON, VisuallyHidden, defineStatusMap, defineWebModule, formatAge, formatRelative, formatTimestamp, satisfiesDeckApi, statusTone, useConfig, useProvider, useProviders, useUiManifest };
export type { CalloutProps, DataTableProps, EmptyStateProps, ErrorStateProps, HealthPillProps, IconProps, KeyValueItem, KeyValueListProps, LoadingStateProps, MeterProps, PageHeaderProps, SectionProps, StatTileProps, StatusBadgeProps, StatusMap, StatusMapData, StatusPresentation, Tone, WebModule, WebModuleManifest };
