// Build index.d.ts, the types of `@deck/sdk`, from the web app's own SDK entry
// (apps/web/src/sdk/index.ts), so a module author type-checks against what deck serves.
// The compiler emits the entry's declarations in memory; rollup-plugin-dts then bundles the
// ones the SDK reaches into one file, inlining deck's own packages and keeping imports of
// the packages in EXTERNAL.
// Usage: node scripts/build-types.mjs   (test/types-lockstep.test.ts keeps index.d.ts current)
import { existsSync, readFileSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { rollup } from "rollup";
import { dts } from "rollup-plugin-dts";
import ts from "typescript";

const fromHere = (path) => fileURLToPath(new URL(path, import.meta.url));
const REPO = fromHere("../../../");
const WEB = join(REPO, "apps/web");
const ENTRY = join(WEB, "src/sdk/index.ts");
/** Where the in-memory declarations live: a path nothing is written to. */
const OUT = join(REPO, ".sdk-types");

const BANNER = "// The types of @deck/sdk, generated by scripts/build-types.mjs from deck's web SDK\n// (apps/web/src/sdk/index.ts). Do not edit: run `pnpm --filter @deck/sdk types:build`.";

/**
 * Packages whose types stay imports rather than being inlined: React, which the author
 * installs, and the two @deck/sdk depends on for types (the icon names and table columns).
 */
export const EXTERNAL = ["react", "lucide-react", "@tanstack/react-table"];

/**
 * `paths` sending each workspace package's exports to its sources, so the compiler emits their
 * declarations too (resolved through node_modules, they would count as external libraries).
 */
function workspacePaths() {
  const paths = {};
  for (const group of ["packages", "apps"]) {
    for (const name of ts.sys.getDirectories(join(REPO, group))) {
      const dir = join(REPO, group, name);
      if (!existsSync(join(dir, "package.json"))) continue;
      const manifest = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
      for (const [subpath, target] of Object.entries(manifest.exports ?? {})) {
        if (typeof target === "string" && /\.tsx?$/.test(target)) paths[`${manifest.name}${subpath.slice(1)}`] = [join(dir, target)];
      }
    }
  }
  return paths;
}

/** The compiler options for the web app's sources, emitting declarations only. */
function compilerOptions() {
  const { config } = ts.readConfigFile(join(WEB, "tsconfig.json"), ts.sys.readFile);
  const { options } = ts.parseJsonConfigFileContent(config, ts.sys, WEB, undefined, join(WEB, "tsconfig.json"));
  return {
    ...options,
    paths: { ...options.paths, ...workspacePaths() },
    noEmit: false,
    declaration: true,
    emitDeclarationOnly: true,
    rootDir: REPO,
    outDir: OUT,
    types: ["vite/client"],
  };
}

/** The entry's declarations (and those of every deck source it reaches), keyed by their path under OUT. */
function emitDeclarations(options) {
  const program = ts.createProgram([ENTRY], options);
  const files = new Map();
  const { diagnostics } = program.emit(undefined, (fileName, text) => files.set(resolve(fileName), text));
  const errors = [...ts.getPreEmitDiagnostics(program), ...diagnostics].filter((d) => d.category === ts.DiagnosticCategory.Error);
  // JSON modules emit nothing (emitSkipped); only errors count.
  if (errors.length > 0) {
    throw new Error(ts.formatDiagnostics(errors, { getCanonicalFileName: (f) => f, getCurrentDirectory: () => REPO, getNewLine: () => "\n" }));
  }
  return files;
}

/** The bundled declarations, as text. */
export async function generateTypes() {
  const options = compilerOptions();
  const files = emitDeclarations(options);
  const toOut = (source) => join(OUT, relative(REPO, source)).replace(/\.tsx?$/, ".d.ts");
  const bundle = await rollup({
    input: toOut(ENTRY),
    external: (id) => EXTERNAL.some((name) => id === name || id.startsWith(`${name}/`)),
    // Modules the SDK reaches but whose types it never uses (the UI primitives, the schema
    // validators) import packages left unresolved; tree-shaking drops them, and the lockstep
    // test checks that the output imports nothing outside EXTERNAL.
    onLog: (level, log, handler) => (log.code === "UNRESOLVED_IMPORT" ? undefined : handler(level, log)),
    plugins: [
      {
        name: "deck-sdk-declarations",
        // Resolve as the compiler did, from the importing declaration's source directory.
        resolveId(id, importer) {
          if (importer === undefined) return id;
          const from = join(REPO, relative(OUT, importer));
          const resolved = ts.resolveModuleName(id, from, options, ts.sys).resolvedModule;
          if (resolved === undefined || resolved.isExternalLibraryImport) return null;
          const declaration = toOut(resolved.resolvedFileName);
          if (!files.has(declaration)) throw new Error(`no declaration emitted for ${id} (from ${from})`);
          return declaration;
        },
        load(id) {
          return files.get(id) ?? null;
        },
      },
      dts({ respectExternal: true }),
    ],
  });
  const { output } = await bundle.generate({ format: "es", banner: BANNER });
  await bundle.close();
  return output[0].code;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await writeFile(fromHere("../index.d.ts"), await generateTypes());
}
